API:
  url: &url 'https://robot-dreams-de-api.herokuapp.com'
  endpoint: '/out_of_stock'
  content_type: &content 'application/json'
  date: &dt '2021-11-17'
  auth: 'JWT'

AUTH:
  url: *url
  endpoint: '/auth'
  content_type: *content
  username: 'rd_dreams'
  password: 'djT6LasE'
  token: 'access_token'

SAVE:
  directory: '/data/'
  file_name: 'out_of_stock'
  date: *dt
  zone: 'bronze'
  project_name: 'project_name'


POSTGRESQL_CONNECTION_PARAMETERS:
  host: &host '192.168.1.35'
  port: '5432'
  database: 'dshop_bu'
  user: 'pguser'
  password: 'secret'

PG_CONNECTION_DSHOP:
  host: *host
  port: '5432'
  database: 'postgres'
  user: 'pguser'
  password: 'secret'

HDFS_WEB_CLIENT:
  url: 'http://127.0.0.1:50070/'
  user: 'user'

TABLE_NAMES:
  - aisles
  - clients
  - departments
  - location_areas
  - orders
  - products
  - store_types
  - stores

TABLES_DSHOP:
  - aisles
  - clients
  - departments
  - orders
  - products